meta:
  title: fusuma template
  author: takao-h
  description: 
  thumbnail: 
  repositoryUrl: 
  sns: ["twitter"]
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  code:
    languages:
      - javascript
      - typescript
      - json
    plugins: []
extends:
  js:
  css:
